version: "3.0"
services:
  web:
    build: .
    ports:
      - "8001:8080"
    restart: on-failure
    depends_on:
      - database
    volumes:
      - ./src/main/resources/application.yml:/app/application.yml

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: weba
      POSTGRES_PASSWORD: weba
    volumes:
      - webadb:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8002:8080"

volumes:
  webadb:
