security:
  cas:
    server:
      base-url: https://login.ugent.be
      protocol-version: 2  # has to be explicitly declared (default = 3)
    service:
      paths:
        logout: /logout
      base-url: http://local.todo.ugent.be:8080
application:
  base-url: https://studententuin.ugent.be

## PostgreSQL
spring:
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
  datasource:
    url: jdbc:postgresql://localhost/weba
    username: weba
    password: weba